name: carwan_dough
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.6.1

dependencies:
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.2
  crystal_navigation_bar: ^1.0.4
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  iconly: ^1.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/products/
    - assets/images/social/

  fonts:

    - family: TheMonster-RpvXo
      fonts:
        - asset: assets/fonts/TheMonster-RpvXo.otf
    - family: NaughtyMonster
      fonts:
        - asset: assets/fonts/NaughtyMonster.otf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
